// Code generated by MockGen. DO NOT EDIT.
// Source: analytics.go

// Package mock_main is a generated GoMock package.
package analytics

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAnalyzer is a mock of Analyzer interface.
type MockAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyzerMockRecorder
}

// MockAnalyzerMockRecorder is the mock recorder for MockAnalyzer.
type MockAnalyzerMockRecorder struct {
	mock *MockAnalyzer
}

// NewMockAnalyzer creates a new mock instance.
func NewMockAnalyzer(ctrl *gomock.Controller) *MockAnalyzer {
	mock := &MockAnalyzer{ctrl: ctrl}
	mock.recorder = &MockAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyzer) EXPECT() *MockAnalyzerMockRecorder {
	return m.recorder
}

// InsertRequest mocks base method.
func (m *MockAnalyzer) InsertRequest(r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InsertRequest", r)
}

// InsertRequest indicates an expected call of InsertRequest.
func (mr *MockAnalyzerMockRecorder) InsertRequest(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRequest", reflect.TypeOf((*MockAnalyzer)(nil).InsertRequest), r)
}
